const coursesCard = [
  {
    cover: "/courseImg/course1.png",
    courseName: "Software Engineering",
    totalTime: "50 lectures (190 hrs)",
    isFree: true,
    credits: 0,
    skills: ["System Design", "C++"],
  },
  {
    cover: "/courseImg/course2.png",
    courseName: "Introduction to DBMS",
    totalTime: "30 lectures (125 hrs)",
    isFree: true,
    credits: 0,
    skills: ["SQL"],
  },
  {
    cover: "/courseImg/course3.png",
    courseName: "HTML, CSS, and Javascript",
    totalTime: "50 lectures (50 hrs)",
    isFree: true,
    credits: 0,
    skills: ["HTML", "CSS", "JavaScript"],
  },
  {
    cover: "/courseImg/course4.png",
    courseName: "Introduction to Mern-Tech Stack and Javascript",
    totalTime: "20 lectures (20 hrs)",
    isFree: true,
    credits: 0,
    skills: ["MongoDB", "Express.js", "React", "Node.js", "Javascript"],
  },
  {
    cover: "/courseImg/course5.png",
    courseName: "Introduction to Programming with ReactJS",
    totalTime: "100 lectures (150 hrs)",
    isFree: true,
    credits: 0,
    skills: ["Javascript", "ReactJS", "Redux", "Hooks"],
  },
  {
    cover: "/courseImg/course1.png",
    courseName: "Learn Advanced Frontend Programming",
    totalTime: "200 lectures (300 hrs)",
    isFree: false,
    credits: 5,
    skills: ["JavaScript", "PWA"],
  },
  {
    cover: "/courseImg/course2.png",
    courseName: "Introduction to Python",
    totalTime: "20 lectures (50 hrs)",
    isFree: false,
    credits: 8,
    skills: ["Python", "Data Structures", "OOP"],
  },
  {
    cover: "/courseImg/course3.png",
    courseName: "Introduction to JAVA",
    totalTime: "80 lectures (200 hrs)",
    isFree: false,
    credits: 10,
    skills: ["Java", "OOP", "File I/O"],
  },
  {
    cover: "/courseImg/course4.png",
    courseName: "Introduction to C++",
    totalTime: "50 lectures (50 hrs)",
    isFree: false,
    credits: 5,
    skills: ["C++", "OOP", "STL"],
  },
  {
    cover: "/courseImg/course5.png",
    courseName: "Android Application Development",
    totalTime: "40 lectures (160 hrs)",
    isFree: false,
    credits: 6,
    skills: ["Java", "Kotlin"],
  },
  {
    cover: "/courseImg/course1.png",
    courseName: "Advanced Java Spring Boot",
    totalTime: "35 lectures (140 hrs)",
    isFree: false,
    credits: 7,
    skills: ["Java", "Spring Framework", "REST API"],
  },
  {
    cover: "/courseImg/course2.png",
    courseName: "Applied Data Science with Python",
    totalTime: "45 lectures (180 hrs)",
    isFree: false,
    credits: 9,
    skills: ["Python", "Pandas", "NumPy"],
  },
  {
    cover: "/courseImg/course3.png",
    courseName: "Artificial Intelligence Fundamentals",
    totalTime: "50 lectures (200 hrs)",
    isFree: false,
    credits: 10,
    skills: ["Machine Learning", "Python", "TensorFlow"],
  },
  {
    cover: "/courseImg/course4.png",
    courseName: "Cyber Security Basics",
    totalTime: "30 lectures (120 hrs)",
    isFree: false,
    credits: 5,
    skills: ["Cryptography"],
  },
  {
    cover: "/courseImg/course5.png",
    courseName: "IBM Cloud Services",
    totalTime: "25 lectures (100 hrs)",
    isFree: false,
    credits: 5,
    skills: ["Cloud Computing", "DevOps"],
  },
  {
    cover: "/courseImg/course1.png",
    courseName: "Machine Learning with TensorFlow",
    totalTime: "60 lectures (240 hrs)",
    isFree: false,
    credits: 12,
    skills: ["Python", "TensorFlow", "Machine Learning"],
  },
  {
    cover: "/courseImg/course2.png",
    courseName: "Comprehensive Salesforce Development",
    totalTime: "70 lectures (280 hrs)",
    isFree: false,
    credits: 14,
    skills: ["Salesforce"],
  },
  {
    cover: "/courseImg/course3.png",
    courseName: "Blockchain Fundamentals",
    totalTime: "40 lectures (160 hrs)",
    isFree: false,
    credits: 8,
    skills: ["Solidity"],
  },
  {
    cover: "/courseImg/course4.png",
    courseName: "Cloud Computing with AWS",
    totalTime: "50 lectures (200 hrs)",
    isFree: false,
    credits: 10,
    skills: ["AWS", "S3"],
  },
];

module.exports = { coursesCard };
